### ISSUE TITLE
NA Map R2 (2017-11-09) pre-release test - Error loading data layer 1 (Geofabric)

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/NorthernAustralia#34]
Error loading data

- Water/Geofabric/Groundwater_Cartography

![slide5](https://user-images.githubusercontent.com/22827786/32645441-614bf7fc-c63b-11e7-811e-27b0c57cb1cf.JPG)

**Comment by AnaBelgun** [comment]
response received on 15 Nov
The system is under heavy load at the moment because we've received several large historic resupplies from the data providers at the same time. They were requested in a staggered fashion (to onboard new data categories), but unfortunately a few providers chose the same day to send them. With large data supplies coming in at that rate, WISKI gets overloaded recalculating time series. 
Hopefully this situation will settle over the next couple of days.
